#  Item to Item collaborative filttering

#### Merging the catalogue data with behaviour insights

In [2]:
from util.filter import create_merged_item_data

create_merged_item_data()

Merged 50 products into filter/item_merged.json


#### Creating vector embeddings

In [3]:
from util import embedding

product_id , embeddings = embedding.create_product_embeddings("filter/item_merged.json")

#### Creating similarity matrix

In [4]:
similarity_matrix = embedding.build_similarity_matrix(embeddings)

In [5]:
print(similarity_matrix)

[[1.         0.33453399 0.66972119 ... 0.54410327 0.53024572 0.41202939]
 [0.33453399 1.         0.38005357 ... 0.41279978 0.32110062 0.36688648]
 [0.66972119 0.38005357 1.         ... 0.4982055  0.63121009 0.47353557]
 ...
 [0.54410327 0.41279978 0.4982055  ... 1.         0.60008368 0.4378505 ]
 [0.53024572 0.32110062 0.63121009 ... 0.60008368 1.         0.51876822]
 [0.41202939 0.36688648 0.47353557 ... 0.4378505  0.51876822 1.        ]]


In [6]:
from util.recommedation import get_similar_products

similar_products = get_similar_products(
    "product-025",
    product_id,
    similarity_matrix,
    k=5
)

print(similar_products)

[('product-016', 0.6956033872276189), ('product-003', 0.6840169597336585), ('product-006', 0.6368867876980795), ('product-042', 0.626900960532745), ('product-024', 0.6077247569853821)]


In [7]:
from util.recommedation import recommend_products
recs = recommend_products(
    "product-025",
    product_id,
    embeddings,
    k=5
)

for r in recs:
    print(r)

{'product_id': 'product-016', 'similarity': np.float64(0.6956033872276186)}
{'product_id': 'product-003', 'similarity': np.float64(0.6840169597336588)}
{'product_id': 'product-006', 'similarity': np.float64(0.6368867876980796)}
{'product_id': 'product-042', 'similarity': np.float64(0.6269009605327448)}
{'product_id': 'product-024', 'similarity': np.float64(0.6077247569853819)}


# User Interactions

#### Creation

In [8]:
import json

user = {
    "user_id": "usr-001",
    "name": "Priya",
    "age": 24,
    "age_group": "18-24",
    "gender": "female",
    "location": {
        "city": "Kolkata",
        "state": "West Bengal",
        "currency": "INR"
    },
    "budget": {
        "total": 10000,
        "per_item_max": 4000,
        "flexibility_percent": 10
    },
    "style_preferences": {
        "categories": ["ethnic", "casual"],
        "avoid": ["western-formal", "heavy-embroidery"],
        "favorite_colors": ["teal", "mustard", "sage-green"],
        "favorite_fabrics": ["cotton", "linen"],
        "occasions": ["college", "casual", "festive"]
    },
    "body_profile": {
        "height_cm": 162,
        "build": "petite",
        "top_size": "S",
        "bottom_size": "28",
        "shoe_size": "38"
    },
    "photo_path": "inputs/priya.jpg",
    "created_at": "2026-06-11T10:00:00Z",
    "last_active": "2026-06-11T10:00:00Z"
}

with open("data/user_profile.json", "w", encoding="utf-8") as f:
    json.dump(user, f, indent=2)

print(
    f"Profile loaded — ₹{user['budget']['total']} budget, "
    f"age {user['age']}, "
    f"styles: {', '.join(user['style_preferences']['categories'])}"
)

Profile loaded — ₹10000 budget, age 24, styles: ethnic, casual


In [1]:
from util.filter import filter_products

filtered_product = filter_products()

print(filtered_product)

{'message': 'Here are some products selected based on your preferences.', 'products': [{'id': 'product-021', 'name': 'Cotton Kurta', 'brand': 'Zara', 'category': 'ethnic', 'price': 1622, 'discount_percent': 23, 'rating': 4.8, 'colors': ['black', 'grey', 'blue'], 'in_stock': True, 'image_url': 'https://picsum.photos/600/800?random=21'}, {'id': 'product-046', 'name': 'Printed Kurta', 'brand': 'W', 'category': 'ethnic', 'price': 2375, 'discount_percent': 1, 'rating': 4.7, 'colors': ['green', 'blue', 'black'], 'in_stock': True, 'image_url': 'https://picsum.photos/600/800?random=46'}, {'id': 'product-050', 'name': 'Straight Jeans', 'brand': 'Anokhi', 'category': 'casual', 'price': 1359, 'discount_percent': 26, 'rating': 4.7, 'colors': ['yellow', 'green', 'white'], 'in_stock': True, 'image_url': 'https://picsum.photos/600/800?random=50'}, {'id': 'product-013', 'name': 'Printed Kurta', 'brand': 'Anokhi', 'category': 'ethnic', 'price': 2473, 'discount_percent': 15, 'rating': 4.5, 'colors': ['n

In [10]:
from agent.graph import create_graph
from langchain_core.messages import HumanMessage

query="Show me the catalogue"
config={
    "configurable":{
        "thread_id":1
    }
}

graph = create_graph()
result=graph.invoke(
    {
        "messages":[HumanMessage(content=query)]
    },
    config=config
)

print(result["messages"][-1].content)

KeyboardInterrupt: 

In [1]:
from agent.tools import collabotative_filttering

collabotative_filttering()

Merged 50 products into filter/item_merged.json


'Item similarity analysis completed successfully.'

In [1]:
from agent.tools import get_similar_products

get_similar_products("product-039")

[{'product_id': 'product-040', 'score': 0.6790600548504041},
 {'product_id': 'product-016', 'score': 0.6540575834053592},
 {'product_id': 'product-031', 'score': 0.6456671350351431},
 {'product_id': 'product-013', 'score': 0.6362398306527006},
 {'product_id': 'product-011', 'score': 0.6344470111109848},
 {'product_id': 'product-010', 'score': 0.6312100921733284},
 {'product_id': 'product-002', 'score': 0.612914038727128},
 {'product_id': 'product-043', 'score': 0.6014093449048202},
 {'product_id': 'product-029', 'score': 0.600083680956566},
 {'product_id': 'product-048', 'score': 0.5639620181688388}]

In [1]:
from agent.tools import get_product_details

get_product_details("product-040")

{'id': 'product-040',
 'name': 'Embroidered Juttis',
 'brand': 'Global Desi',
 'category': 'footwear',
 'sub_category': 'flats',
 'price': 417,
 'original_price': 609,
 'discount_percent': 32,
 'colors': ['white', 'green', 'beige'],
 'sizes_available': ['XS', 'S', 'M', 'L'],
 'fabric': 'silk-blend',
 'occasion': ['outing', 'office', 'casual'],
 'rating': 4.0,
 'review_count': 816,
 'in_stock': True,
 'image_url': 'https://picsum.photos/600/800?random=40'}

In [1]:
from agent.tools import get_top_viewed_products

res=get_top_viewed_products('usr-20260617094214')
# len(res)
res

[{'product_id': 'product-001', 'view_count': 2},
 {'product_id': 'product-002', 'view_count': 2},
 {'product_id': 'product-003', 'view_count': 2},
 {'product_id': 'product-004', 'view_count': 2},
 {'product_id': 'product-005', 'view_count': 2},
 {'product_id': 'product-006', 'view_count': 2},
 {'product_id': 'product-007', 'view_count': 2},
 {'product_id': 'product-008', 'view_count': 2},
 {'product_id': 'product-009', 'view_count': 2},
 {'product_id': 'product-010', 'view_count': 2}]

In [1]:
from util import cart

cart.add_to_cart("product-002")

'Added product-002 to cart'

In [2]:
cart.get_cart()

{'items': [{'product_id': 'product-002',
   'name': 'Cotton Kurta',
   'price': 2082,
   'quantity': 1,
   'subtotal': 2082,
   'image_url': 'https://picsum.photos/600/800?random=2'}],
 'total': 2082,
 'item_count': 1}

In [1]:
from agent.tools import get_user_profile

get_user_profile()

{'user_id': 'usr-20260617150321',
 'name': 'miya',
 'age': 24,
 'age_group': '18-24',
 'gender': 'female',
 'location': {'city': 'Kolkata', 'state': '', 'currency': 'INR'},
 'budget': {'total': 20000, 'per_item_max': 5000, 'flexibility_percent': 10},
 'style_preferences': {'categories': ['ethnic'],
  'avoid': [],
  'favorite_colors': [],
  'favorite_fabrics': [],
  'occasions': ['college', 'casual', 'office']},
 'body_profile': {},
 'photo_path': '',
 'created_at': '2026-06-17T09:33:21.292986+00:00',
 'last_active': '2026-06-17T09:33:21.292986+00:00'}